#!/usr/bin/env sh

export NVM_DIR

NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" # try to find nvm directory

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # load nvm if it exists

PKG_MGR=""
SUPPORTED_PKG_MGRS="pnpm yarn npm"

for pm in $SUPPORTED_PKG_MGRS; do
    if command -v "$pm" >/dev/null; then
        PKG_MGR="$pm"
        break
    fi
done

if [ "$PKG_MGR" = "pnpm" ]; then
    pnpm run prettier
    pnpm run build
elif [ "$PKG_MGR" = "yarn" ]; then
    yarn run prettier
    yarn run build
elif [ "$PKG_MGR" = "npm" ]; then
    npm run prettier
    npm run build
else
    echo "Unsupported package manager: $PKG_MGR"
fi
